Server:
  Port: 8075
  BindIp: ""

Observability:
  Port: 9009
  BindIp: ""

DataDir: "./data"

Env:
  LogLevel: "info"
  Production: false

TaskRunner:
  Parallelism: 2
  QueueSize: 20
  HistorySize: 50
  TagReadWorkers: 0
